package tools.deemwar.mochallama;

/**
 * Real token-usage accounting for one inference, as reported by the native
 * bridge (these are exact counts, not estimates):
 *
 * <ul>
 *   <li>{@code promptTokens} — tokens in the formatted prompt that was decoded</li>
 *   <li>{@code completionTokens} — tokens actually generated by the model</li>
 *   <li>{@code totalTokens} — {@code promptTokens + completionTokens}</li>
 * </ul>
 */
public final class Usage {

    private final int promptTokens;
    private final int completionTokens;
    private final int totalTokens;

    public Usage(int promptTokens, int completionTokens, int totalTokens) {
        this.promptTokens = promptTokens;
        this.completionTokens = completionTokens;
        this.totalTokens = totalTokens;
    }

    public int promptTokens()     { return promptTokens; }
    public int completionTokens() { return completionTokens; }
    public int totalTokens()      { return totalTokens; }

    @Override
    public String toString() {
        return "Usage{prompt=" + promptTokens
                + ", completion=" + completionTokens
                + ", total=" + totalTokens + "}";
    }
}
